# Generated by Django 6.0.4 on 2026-05-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_device_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='assignment',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
