# Generated by Django 6.0.4 on 2026-05-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_remove_device_qr_code_assignment_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
