# Generated by Django 6.0.4 on 2026-05-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_device_inventory_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
