# Generated by Django 6.0.4 on 2026-05-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_assignment_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
