# Generated by Django 6.0.4 on 2026-05-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_device_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='old_inventory_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
