# Generated by Django 6.0.4 on 2026-05-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_device_old_inventory_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
