# Generated by Django 6.0.4 on 2026-05-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_alter_device_inventory_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_auto_inventory',
            field=models.BooleanField(default=False),
        ),
    ]
